### ISSUE TITLE
Exception when processing orders

### ISSUE THREAD

**Issue by mickeprag** [30350n/inventree_lectronz#1]
Hi,

Thank you for this plugin and your work!

I am getting this exception in the log when the plugin is importing orders
```
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/django_q/worker.py", line 103, in worker
    res = f(*task["args"], **task["kwargs"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inventree/src/backend/InvenTree/plugin/registry.py", line 180, in call_plugin_function
    return plugin_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/inventree_lectronz/plugin.py", line 212, in sync_lectronz_orders
    create_sales_order(lectronz, order, self.products, target_date)
  File "/usr/local/lib/python3.11/site-packages/inventree_lectronz/create_sales_order.py", line 70, in create_sales_order
    create_line_item(sales_order, parts, line_items, order, item, products)
  File "/usr/local/lib/python3.11/site-packages/inventree_lectronz/create_sales_order.py", line 171, in create_line_item
    line_item = SalesOrderLineItem.objects.create(order=sales_order, **line_item_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/inventree/src/backend/InvenTree/order/models.py", line 1398, in save
    super().save(*args, **kwargs)
  File "/home/inventree/src/backend/InvenTree/InvenTree/models.py", line 167, in save
    super().save(*args, **kwargs)
  File "/home/inventree/src/backend/InvenTree/InvenTree/models.py", line 122, in save
    super().save(*args, **kwargs)
  File "/root/.local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/root/.local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/root/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
django.db.utils.DataError: value too long for type character varying(100)
```

Seems like some text is longer than the maximum 100 characters in the database?

**Comment by 30350n** [comment]
Thanks for checking out this project! I think you might be one of the first people trying/using this extension other than me, so you might run into some issues. (Although it's been working fine for me, for the past 8 months atleast ^^).

As you already figured, this is particularily caused by the sales order line item reference exceeding it's `max_length` of 100 characters. I currently set the reference like this: https://github.com/30350n/inventree_lectronz/blob/8e23b2feaa5780aba1772423bacfe70dbcb59f28/inventree_lectronz/create_sales_order.py#L115-L118

So it contains the product name, as well as all the product options and their selected values. So in your case, this is probably caused by a lot of product options I would assume?

Anyways, what I've done for now is limit the reference size to 100 characters, so the error should not appear in [v1.1](https://github.com/30350n/inventree_lectronz/releases/tag/1.1) anymore. I've also set limits for some other fields that could become problematic.

Please let me know if this fixes the issue for you ^^

**Comment by 30350n** [comment]
Oh also as a headsup: This does not support the new "Platform" UI InvenTree is currently pushing for (yet). Because I'm personally still on the old UI.

**Comment by mickeprag** [comment]
Wow. That was fast! 
I will update and monitor if I see any other issues, although I don't have that many orders on Lectronz so it may take a while.

Thank you for your efforts!

**Comment by mickeprag** [comment]
I am closing this issue since I have not had any issues after updating to the latest version. Thanks!
